Repository vapor/fluent, pull requests merged in 2020-04, with the labels that each got.

#668 update to Vapor authenticator changes
  Package.swift
  Sources/Fluent/Deprecated.swift
  Sources/Fluent/Fluent+Sessions.swift
  Sources/Fluent/ModelAuthenticatable.swift
  Sources/Fluent/ModelTokenAuthenticatable.swift
Labels: bug, enhancement

#672 Update to Vapor 4 GM
  Package.swift
  Sources/Fluent/Deprecated.swift
  Sources/Fluent/Fluent+Sessions.swift
  Sources/Fluent/ModelAuthenticatable.swift
  Sources/Fluent/ModelTokenAuthenticatable.swift
  Tests/FluentTests/OperatorTests.swift
  Tests/FluentTests/PaginationTests.swift
  Tests/FluentTests/RepositoryTests.swift
  Tests/FluentTests/SessionTests.swift
  Tests/FluentTests/TestDatabase.swift
Labels: enhancement, semver-major

#677 Fix deprecated renamed fix for ModelTokenAuthenticatable
  Sources/Fluent/Deprecated.swift
Labels: enhancement, semver-patch
